package com.spring.cc.entity;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

import com.spring.cc.dataTypes.RealGEZ;
import com.spring.cc.entity.Movimento.tipoMovimento;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;

@Entity
public class ContoCorrente {
	


	@Id
	@GeneratedValue(strategy= GenerationType.IDENTITY)
	private Integer numeroConto;
	
	@Column(nullable = false)
	private Double saldo;
	
	@Column(nullable = false)
	private LocalDateTime dataApertura;
	
	//Optional = false, because we need obv the 'intestatario' on the CC
	@ManyToOne(optional= false)
	private Utente intestatario;
	
	@ManyToOne
	private Utente cointestatario;
	
	@OneToMany(mappedBy= "contoAssociato", cascade= CascadeType.ALL, orphanRemoval= true)
	private List<Movimento> listaMovimenti = new ArrayList<>();
	
	
    public void modificaSaldoCC(Double nuovoSaldo, Utente tecnico) {
    	
    	//Checking the case of negative MAX -5000 euro on CC account Bank
    	if(nuovoSaldo < - 5000)
    		
    		throw new RuntimeException("ATTENZIONE ! Non è fisicamente possibile superare in negativo il LIMITE imposto dalla banca\nMAX NEGATIVE EURO: - 5000 euro ");
    	
    	double calcoloSaldo = nuovoSaldo - this.saldo;
    	
    	if (this.saldo.equals(nuovoSaldo) || calcoloSaldo == 0) return;
    
    
    	//Adding the logic, to check the type of operation if the 'calcoloSaldo > 0'
    	Movimento.tipoMovimento tipologiaOperazione = (calcoloSaldo > 0)? tipoMovimento.versamento : tipoMovimento.prelievo;
    	
    	
    	//After we deducted the type of operation, we can create finally the Movimento OBJ
 
    	Movimento mov = new Movimento();
    	
    	//Null because is generated by the Database
    	mov.setIdMovimento(null);
    	mov.setOperazione(tipologiaOperazione);
    	
    	//Settign the ABSOLUTE value of the calcoloSaldo
    	mov.setImporto(new RealGEZ(Math.abs(calcoloSaldo)));
    	

    	mov.setDataOperazione(LocalDateTime.now());
    	
    	mov.setOperatoreBanca(tecnico);
    	mov.setContoAssociato(this);
    	
    	
    	//Adding correctly the data on the CC Bank Account
    	this.listaMovimenti.add(mov); 
        this.saldo = nuovoSaldo;
    	
    	
    	//Calculating the ImportoMora of CC
    	if (tipologiaOperazione == tipoMovimento.prelievo && this.saldo < 0) {
    		
    		//Calculate with the 5%
            double importoMora = Math.abs(calcoloSaldo) * 0.05;  
            
            Movimento mor = new Movimento();
            mor.setOperazione(Movimento.tipoMovimento.prelievo);
            mor.setImporto(new RealGEZ(importoMora));
            mor.setDataOperazione(LocalDateTime.now());
            
            mor.setOperatoreBanca(tecnico);
            mor.setContoAssociato(this);
            

            this.listaMovimenti.add(mor);
            
            //Substract the ImportoMora from the saldo
            this.saldo -= importoMora; 
        }
	
    	
    	
    	
    }
	
    public ContoCorrente() {}
    
	public ContoCorrente(Integer numeroConto, Double saldoIniziale, LocalDateTime dataApertura, Utente intestatario) {
		
		this.numeroConto = numeroConto;
		this.intestatario = intestatario;
		this.saldo = 0.0;
		this.dataApertura = dataApertura;
		
		if (saldoIniziale != null && saldoIniziale > 0) {
	        this.modificaSaldoCC(saldoIniziale, intestatario);

	}
	}

	public Integer getNumeroConto() {
		return numeroConto;
	}

	public void setNumeroConto(Integer numeroConto) {
		this.numeroConto = numeroConto;
	}

	public Double getSaldo() {
		return saldo;
	}

	public void setSaldo(Double saldo) {
		this.saldo = saldo;
	}

	public LocalDateTime getDataApertura() {
		return dataApertura;
	}

	public void setDataApertura(LocalDateTime dataApertura) {
		this.dataApertura = dataApertura;
	}
    

	public Utente getIntestatario() {
		return intestatario;
	}

	public void setIntestatario(Utente intestatario) {
		this.intestatario = intestatario;
	}

	public Utente getCointestatario() {
		return cointestatario;
	}

	public void setCointestatario(Utente cointestatario) {
		this.cointestatario = cointestatario;
	}
	
	public List<Movimento> getListaMovimenti() {
		return listaMovimenti;
	}

	public void setListaMovimenti(List<Movimento> listaMovimenti) {
		this.listaMovimenti = listaMovimenti;
	}

	
	
	
	
	
	
	
	
	

}
