//Creation of class Persona, example with attributes and methods manipulation
package corsoBase;

public class Lezione5_0 {
	
	//Creation of class Persona, with declaration of attributes without visibilty
	
	//We add final form, to implement the immutable form in nome, and is dosen't appear on Getter - Setter, and invocated to modify it. Assignable only one time on the builder.
	private final String nome; 
    
    //Case we use final and static toghether we have to assign a value -> private static final String nome = "name"

	private int eta;
	private double peso;
	
	//Creation of builder(s), generated by Source -> Generate Constructor using fields -> adding the one we need and where (position of generation
	public Lezione5_0(String nome, int eta, double peso) {
		
		
		this.nome = nome;
		this.eta = eta;
		this.peso = peso;
		
	}

	//In this case if we don't declarate nothing (eta) it will be generated as default. In this case equal to zero.
	public Lezione5_0(String nome, double peso) {
		
		this.nome = nome;
		this.peso = peso;
		eta = 0;
		
	}
	
	//Creation of methods, obviously the setter attributes read the attributes. Generated by Source -> Generate Getters and Setters using fields -> adding the get and set we want in evry attribute
	
    //Creation of Getter and Setter, for read and modify the attributes of the class
	public int getEta() {
		return eta;
	}

	public void setEta(int eta) {
		
		if (eta >= this.eta)
			this.eta = eta;
	}

	public double getPeso() {
		return peso;
	}

	public void setPeso(double peso) {
		this.peso = peso;
	}
	
	//In this case, for education, we manage the case that the name it can't be setted because is assigned from the birth
	public String getNome() {
		return this.nome;
	}
	
	

    //Creation of the toString form
	@Override
	public String toString() {
		return "Lezione5_0: [nome= " + this.nome + ", eta= " + eta + ", peso= " + peso + "]";
	}
	
	//Operative methods, that not are in the Source part. 
	
	//We go to increment the eta + 1
	public void cresce() {
	
		this.eta ++;
}
	//The compilator go to see name of the method and the given paramter, if are equal -> Error: duplicates 
	//We go to increment the eta with a parameter given 'n', it still void and with the same name  -> OverLoading 
	public void cresce(int n) {
		
		this.eta += n;
	}
}





/* MAIN PART :

package corsoBase;

public class Lezione5_1 {

	public static void main(String[] args) {
		Lezione5_0 p1= new Lezione5_0 ("mario",20,70);
		System.out.println(p1);
		
		p1.setEta(-30);
		
		System.out.println(p1);
		
		//In this case we comment this form, because is not applicable
		//p1.nome = "gianni";
		
		System.out.println(p1);
		
		p1.cresce(5);
		System.out.println(p1);
		
		
		Lezione5_0 baby = new Lezione5_0 ("Giulia",3.2);
		
		System.out.println(baby);
		
		baby.cresce();
		
		System.out.println(baby);
		}

	}


OUTPUT:

Lezione5_0: [nome= mario, eta= 20, peso= 70.0]
Lezione5_0: [nome= mario, eta= 20, peso= 70.0]
Lezione5_0: [nome= mario, eta= 20, peso= 70.0]
Lezione5_0: [nome= mario, eta= 25, peso= 70.0]
Lezione5_0: [nome= Giulia, eta= 0, peso= 3.2]
Lezione5_0: [nome= Giulia, eta= 1, peso= 3.2]

 */
	
	
	
	
