package Spring;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;


/* * SpringDevApplicationTests - Spring Boot Integration Test
    ? Default test class generated by Spring Boot to verify that the application context loads correctly.

    ! 1. contextLoads(), acts as a sanity check; it executes an empty test body effectively asserting that the Spring Container starts up without throwing exceptions.
*/


@SpringBootTest
class testSpringDevApplicationTests {

	@Test
	void contextLoads() {
	}

}
